Added saving of features
jorenham/fingerblox pull request #50
Opened 2017-03-31 01:04 UTC by julianfx

New button in imagedisplay activity prompts for filename and saves
keypoints and descriptors as json

As described in issue #17

2017-03-31 09:58 UTC, jrauhamaa commented
Since we are only saving data files here, do you think it makes sense to ask the user for file names?

2017-03-31 09:59 UTC, jrauhamaa commented on FingerBlox/app/src/main/java/org/fingerblox/fingerblox/ImageDisplayActivity.java
> +            File keypointsFile = new File(fileDir, fileName+"_keypoints");
Is this code duplicated on purpose?

2017-04-01 16:20 UTC, jorenham approved these changes

2017-04-01 17:43 UTC, jrauhamaa requested changes
- remove duplicated code
- would be nice if the code would generate automatic filename (e.g. an uuid) instead of asking the user given that the user won't be able to access the files. 
- would be nice if the user got notified of successful save

2017-04-01 21:43 UTC, julianfx commented
-Added loading files for the matching part
-Removed the duplicate code in saveFeatures
-Added toast messages for save success and failure

@jrauhamaa automatic filename generation isn't really useful right now, but can be easily added when it is necessary. With the known filename, you can easily see which one to match with, which you can't with the automatically generated one.

2017-04-02 09:46 UTC, jorenham commented
You got some conflict

2017-04-03 11:40 UTC, merged