3 issue
jorenham/fingerblox pull request #66
Opened 2017-04-06 20:43 UTC by luHub

Roles Changed to Android Developer

2017-04-07 07:56 UTC, jorenham requested changes
Like said before, the achievements should be removed, and the names and roles should be put in a table

2017-04-07 09:19 UTC, luHub commented
Ok will put them on a table

2017-04-07 09:36 UTC, luHub commented
Changed to table layout.
[(https://github.com/jorenham/fingerblox/pull/66/files](https://github.com/jorenham/fingerblox/pull/66/files)

2017-04-18 10:03 UTC, jorenham approved these changes

2017-04-18 10:03 UTC, merged